### ISSUE TITLE
关于对c/c++的支持

### ISSUE THREAD

**Issue by TimeTrapzz** [yezige/vscode-theme-green-eyecare#2]
作者您好，您的主题很好看，能否考虑加入对c/c++的支持呢，十分感谢！

**Comment by yezige** [comment]
当然可以，我试试打开下c++，理论上时可以的，我只是没有测试而已

**Comment by TimeTrapzz** [comment]
> 当然可以，我试试打开下c++，理论上时可以的，我只是没有测试而已

有一点点小问题，像string,cin,cout这类的都是灰色的，强迫症看着很难受😂

**Comment by yezige** [comment]
好的，今天我试试优化一下，确实没有测试c++抱歉

**Comment by yezige** [comment]
> 有一点点小问题，像string,cin,cout这类的都是灰色的，强迫症看着很难受😂

老哥能贴一段c/c++的代码吗？我测试用，最好是整个文件，我在github上下了几个热门的c++项目，大概测试了一下，但不太懂c，怕覆盖不全。

**Comment by TimeTrapzz** [comment]
> > 有一点点小问题，像string,cin,cout这类的都是灰色的，强迫症看着很难受😂
> 
> 老哥能贴一段c/c++的代码吗？我测试用，最好是整个文件，我在github上下了几个热门的c++项目，大概测试了一下，但不太懂c，怕覆盖不全。
emmm，我没写过项目，我是学算法竞赛的，代码量很小。。。

**Comment by yezige** [comment]
![微信截图_20200709103231](https://user-images.githubusercontent.com/11436166/86990641-9aef8180-c1cf-11ea-8010-2b893e62c359.png)

差不多就这样了 @TimeTrapzz

**Comment by TimeTrapzz** [comment]
可以的大佬，十分感谢！

**Comment by yezige** [comment]
> 可以的大佬，十分感谢！

感谢反馈
And
新版已发布[v0.0.5](https://github.com/yezige/vscode-theme-green-eyecare/releases/tag/v0.0.5)
